### ISSUE TITLE
Tests fail when run in powershell

### ISSUE THREAD

**Issue by rdmueller** [jlstrater/groovy-spring-boot-restdocs-example#2]
just as a sidenote:
the tests fail when run in windows 10 powershell. Everything is fine when run in bash on windows.

test and document get of a list from example endpoint
org.springframework.restdocs.payload.PayloadHandlingException: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x22
 at [Source: [B@4837d67d; line: 8, column: 20]
	at org.springframework.restdocs.payload.JsonContentHandler.readContent(JsonContentHandler.java:84)
	at org.springframework.restdocs.payload.JsonContentHandler.findMissingFields(JsonContentHandler.java:49)
	at org.springframework.restdocs.payload.AbstractFieldsSnippet.validateFieldDocumentation(AbstractFieldsSnippet.java:112)
	at org.springframework.restdocs.payload.AbstractFieldsSnippet.createModel(AbstractFieldsSnippet.java:73)
	at org.springframework.restdocs.snippet.TemplatedSnippet.document(TemplatedSnippet.java:64)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:101)
	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:177)
	at sample.web.ExampleControllerSpec.test and document get of a list from example endpoint(ExampleControllerSpec.groovy:77)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x22
 at [Source: [B@4837d67d; line: 8, column: 20]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3473)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3480)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_3fast(UTF8StreamJsonParser.java:3286)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2466)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2414)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:514)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:625)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:496)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:603)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:510)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2819)
	at org.springframework.restdocs.payload.JsonContentHandler.readContent(JsonContentHandler.java:81)
	... 7 more

**Comment by jlstrater** [comment]
hmm... Thanks. I'll have to take a look at this. I don't normally use powershell, but I'll see what I can find.

**Comment by rdmueller** [comment]
Maybe I find the reason when I dive deeper into your code...

**Comment by jlstrater** [comment]
It looks like this might be part of the problem. http://stackoverflow.com/questions/35597622/jsonparseexception-invalid-utf-8-middle-byte-0x20-with-mockmvc-and-maven This example is using one of the early versions of spring rest docs, 1.0.1.RELEASE and the bug fix comes in 1.0.2 Updating the project to the newest version of spring rest docs is on my todo list.

**Comment by rdmueller** [comment]
great. thanx for the update!
